In [1]:
import datetime as dt
import scipy.stats as stats
import matplotlib.pyplot as plt
from matplotlib import style
import pandas as pd
import pandas_datareader.data as web
from scipy.stats import skew
from scipy.stats import kurtosis
import seaborn as sns
import numpy as np

In [7]:
energy_df = pd.read_csv('energy_data.csv')
fin_df = pd.read_csv('fin_data.csv')
mater_df = pd.read_csv('mater_data.csv')
cons_stap_df = pd.read_csv('cons_stap_data.csv')
indust_df = pd.read_csv('indust_data.csv')
comms_df = pd.read_csv('comms_data.csv')
real_df = pd.read_csv('real_data.csv')
tech_df = pd.read_csv('tech_data.csv')
util_df = pd.read_csv('util_data.csv')
cons_disc_df = pd.read_csv('cons_disc_data.csv')
health_df = pd.read_csv('health_data.csv')

energy_df['sector'] = 'ENERGY'
energy_df['returns'] = energy_df['close'].pct_change()
energy_df['returns'] = energy_df['returns'] * 100
energy_df.volume = energy_df.volume.astype(float)

fin_df['sector'] = 'FIN'
fin_df['returns'] = fin_df['close'].pct_change()
fin_df['returns'] = fin_df['returns'] * 100
fin_df.volume = fin_df.volume.astype(float)

mater_df['sector'] = 'MATER'
mater_df['returns'] = mater_df['close'].pct_change()
mater_df['returns'] = mater_df['returns'] * 100
mater_df.volume = mater_df.volume.astype(float)

cons_stap_df['sector'] = 'CONS STAP'
cons_stap_df['returns'] = cons_stap_df['close'].pct_change()
cons_stap_df['returns'] = cons_stap_df['returns'] * 100
cons_stap_df.volume = cons_stap_df.volume.astype(float)

indust_df['sector'] = 'INDUST'
indust_df['returns'] = indust_df['close'].pct_change()
indust_df['returns'] = indust_df['returns'] * 100
indust_df.volume = indust_df.volume.astype(float)

comms_df['sector'] = 'COMMS'
comms_df['returns'] = comms_df['close'].pct_change()
comms_df['returns'] = comms_df['returns'] * 100
comms_df.volume = comms_df.volume.astype(float)

real_df['sector'] = 'REAL'
real_df['returns'] = real_df['close'].pct_change()
real_df['returns'] = real_df['returns'] * 100
real_df.volume = real_df.volume.astype(float)

tech_df['sector'] = 'TECH'
tech_df['returns'] = tech_df['close'].pct_change()
tech_df['returns'] = tech_df['returns'] * 100
tech_df.volume = tech_df.volume.astype(float)

util_df['sector'] = 'UTIL'
util_df['returns'] = util_df['close'].pct_change()
util_df['returns'] = util_df['returns'] * 100
util_df.volume = util_df.volume.astype(float)

cons_disc_df['sector'] = 'CONS DISC'
cons_disc_df['returns'] = cons_disc_df['close'].pct_change()
cons_disc_df['returns'] = cons_disc_df['returns'] * 100
cons_disc_df.volume = cons_disc_df.volume.astype(float)

health_df['sector'] = 'HEALTH'
health_df['returns'] = health_df['close'].pct_change()
health_df['returns'] = health_df['returns'] * 100
health_df.volume = health_df.volume.astype(float)

stocks_df = pd.concat([energy_df, fin_df, mater_df, cons_stap_df, indust_df, comms_df, real_df, tech_df, util_df, cons_disc_df, health_df], sort=False)

#Set index
stocks_df.set_index(['date'], inplace=True)

#Print DataFrame
stocks_df

symbol       close        high         low        open      volume  \
date                                                                            
2013-04-29    SLB   64.298744   64.515881   63.352024   63.890525   5212200.0   
2013-04-30    SLB   64.646164   64.811188   63.699444   64.420341   7392800.0   
2013-05-01    SLB   64.090292   64.429026   63.699444   64.211889   6586500.0   
2013-05-02    SLB   64.489825   64.776446   63.803670   64.116348   4641400.0   
2013-05-03    SLB   65.766593   66.357207   65.149922   65.175979   6582600.0   
2013-05-06    SLB   66.148755   66.374578   65.558141   65.766593   4501800.0   
2013-05-07    SLB   66.782796   67.269184   66.365892   66.522231   5866100.0   
2013-05-08    SLB   67.390781   67.477636   66.470118   66.765425   4793800.0   
2013-05-09    SLB   67.095474   67.451580   66.652514   67.295241   4382700.0   
2013-05-10    SLB   66.721998   66.913079   65.862133   66.826224   6331900.0   
2013-05-13    SLB   66.913079   67.234442   66.530917   66.652514   8105600.0   
2013-05-14    SLB   66.756740   67.112845   66.513546   66.643828   6602300.0   
2013-05-15    SLB   65.731851   66.209553   65.110838   65.653681   9423800.0   
2013-05-16    SLB   65.375745   66.157440   65.202035   65.801335   6200800.0   
2013-05-17    SLB   65.783964   66.157440   65.037011   65.922932   9533300.0   
2013-05-20    SLB   67.243128   67.299583   65.506028   65.627625   9940800.0   
2013-05-21    SLB   66.947821   67.607919   66.591715   67.217071   6334800.0   
2013-05-22    SLB   65.644996   67.564491   65.236777   66.834909   9235500.0   
2013-05-23    SLB   65.471286   65.532084   64.116348   64.654849   6712900.0   
2013-05-24    SLB   64.845930   65.037011   63.977380   64.854616   6632100.0   
2013-05-28    SLB   65.488657   66.165257   65.358374   65.896875   6700100.0   
2013-05-29    SLB   65.123866   65.419173   64.515881   64.984898   4889900.0   
2013-05-30    SLB   64.976213   65.314947   64.229260   64.776446   5747400.0   
2013-05-31    SLB   63.430194   64.715648   63.421508   64.611422   7897400.0   
2013-06-03    SLB   63.892697   64.136928   63.443485   63.840361   8164000.0   
2013-06-04    SLB   63.543795   64.163096   63.299563   63.796749   9450800.0   
2013-06-05    SLB   62.959384   63.770581   62.889603   63.325731   7499400.0   
2013-06-06    SLB   63.936309   63.936309   62.627927   62.907048   7292900.0   
2013-06-07    SLB   64.485830   64.847816   63.927587   64.581778   6703700.0   
2013-06-10    SLB   63.936309   64.887068   63.770581   64.642836   6263700.0   
...           ...         ...         ...         ...         ...         ...   
2018-11-26    LLY  112.380000  113.600000  110.970000  111.260000   3296174.0   
2018-11-27    LLY  114.220000  114.250000  111.710000  112.280000   3263212.0   
2018-11-28    LLY  115.530000  115.830000  113.760000  114.730000   4814474.0   
2018-11-29    LLY  117.000000  117.930000  114.970000  115.300000   4688290.0   
2018-11-30    LLY  118.640000  118.710000  116.220000  117.610000   8965653.0   
2018-12-03    LLY  118.520000  118.690000  117.540000  118.640000   4290056.0   
2018-12-04    LLY  116.520000  119.840000  116.320000  118.650000   5676621.0   
2018-12-06    LLY  115.840000  115.990000  112.980000  115.320000   5064370.0   
2018-12-07    LLY  113.580000  115.780000  112.774100  115.530000   4128118.0   
2018-12-10    LLY  114.090000  114.650000  111.020000  113.600000   3832638.0   
2018-12-11    LLY  114.500000  115.620000  113.922000  114.840000   3806777.0   
2018-12-12    LLY  114.340000  115.740000  114.270000  115.480000   3758775.0   
2018-12-13    LLY  114.860000  115.150000  113.840000  114.620000   3609870.0   
2018-12-14    LLY  111.930000  114.580000  111.240000  114.290000   5306062.0   
2018-12-17    LLY  108.360000  111.300000  107.720000  111.210000   6121672.0   
2018-12-18    LLY  106.500000  109.660000  105.670000  109.430000   6864411.0   
2018-12-19    LLY  109.110000  111.540000 

1. Are there variables that are particularly significant in terms of explaining the answer to your project question? Are there strong correlations between pairs of independent variables, or between an independent and a dependent variable? 

In [12]:
np.corrcoef(x=energy_df.volume,y=energy_df.close)

array([[ 1.       , -0.2185395],
       [-0.2185395,  1.       ]])

In [13]:
np.corrcoef(x=fin_df.volume,y=fin_df.close)

array([[ 1.        , -0.18566197],
       [-0.18566197,  1.        ]])

In [14]:
np.corrcoef(x=mater_df.volume,y=mater_df.close)

array([[ 1.        , -0.41946716],
       [-0.41946716,  1.        ]])

In [15]:
np.corrcoef(x=cons_stap_df.volume,y=cons_stap_df.close)

array([[ 1.        , -0.08158069],
       [-0.08158069,  1.        ]])

In [16]:
np.corrcoef(x=indust_df.volume,y=indust_df.close)

array([[ 1.        , -0.25512831],
       [-0.25512831,  1.        ]])

In [17]:
np.corrcoef(x=comms_df.volume,y=comms_df.close)

array([[ 1.        , -0.06053031],
       [-0.06053031,  1.        ]])

In [18]:
np.corrcoef(x=util_df.volume,y=util_df.close)

array([[ 1.        , -0.24595779],
       [-0.24595779,  1.        ]])

In [19]:
np.corrcoef(x=tech_df.volume,y=tech_df.close)

array([[1.        , 0.01676053],
       [0.01676053, 1.        ]])

In [20]:
np.corrcoef(x=real_df.volume,y=real_df.close)

array([[ 1.        , -0.29694408],
       [-0.29694408,  1.        ]])

In [21]:
np.corrcoef(x=cons_disc_df.volume,y=cons_disc_df.close)

array([[ 1.        , -0.16177993],
       [-0.16177993,  1.        ]])

In [22]:
np.corrcoef(x=health_df.volume,y=health_df.close)

array([[ 1.        , -0.33769373],
       [-0.33769373,  1.        ]])

In [25]:
energy_df.returns.describe()

0.03193340852829769

In [40]:
fin_df.returns.describe()

count    14359.000000
mean         0.052287
std          2.370118
min        -91.450096
25%         -0.713740
50%          0.062112
75%          0.840527
max        100.864382
Name: returns, dtype: float64

In [41]:
mater_df.returns.describe()

count    12724.000000
mean         0.057234
std          4.483879
min        -53.055609
25%         -0.955214
50%          0.038854
75%          1.017915
max        435.533467
Name: returns, dtype: float64

In [42]:
cons_stap_df.returns.describe()

count    13777.000000
mean         0.037441
std          3.088945
min        -83.048467
25%         -0.586042
50%          0.038800
75%          0.666427
max        286.798947
Name: returns, dtype: float64

In [43]:
indust_df.returns.describe()

count    14359.000000
mean         0.065235
std          3.750546
min        -86.347689
25%         -0.788511
50%          0.062972
75%          0.921637
max        360.074294
Name: returns, dtype: float64

In [45]:
comms_df.returns.describe()

count    14224.000000
mean         0.053752
std          2.443496
min        -95.511213
25%         -0.749174
50%          0.059330
75%          0.876636
max         89.957403
Name: returns, dtype: float64

In [44]:
util_df.returns.describe()

count    14359.000000
mean         0.025717
std          2.078478
min        -64.263232
25%         -0.670255
50%          0.065920
75%          0.772859
max        138.457207
Name: returns, dtype: float64

In [46]:
tech_df.returns.describe()

count    14359.000000
mean         0.081115
std          2.722593
min        -88.603824
25%         -0.766313
50%          0.086870
75%          0.996741
max         55.372784
Name: returns, dtype: float64

In [47]:
real_df.returns.describe()

count    13128.000000
mean         0.032446
std          2.475463
min        -65.196218
25%         -0.678134
50%          0.085540
75%          0.788160
max        200.571792
Name: returns, dtype: float64

In [48]:
cons_disc_df.returns.describe()

count    14359.000000
mean         0.054433
std          3.643281
min        -85.478780
25%         -0.708241
50%          0.034928
75%          0.819174
max        316.455311
Name: returns, dtype: float64

In [49]:
health_df.returns.describe()

count    14359.000000
mean         0.041147
std          2.026478
min        -90.067630
25%         -0.637814
50%          0.053409
75%          0.771461
max         68.503415
Name: returns, dtype: float64